name: Daily Build Workflow

on:
    schedule:
        - cron: "0 * * * *"
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - run: echo clone code
            - run: echo build code and unit test
            - run: echo check for code quality and code coverage
            - run: echo check security issues by code scanning
            - run: deploy to dev environment
            - run: trigger tests
